<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Role;
use App\Models\Permission;

class FrontendDashboardRolePermissionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        // 1- create frontend dashboard role
       $frontendRole = Role::create([
            'name' => 'frontend_dashboard',
            'display_name' => 'Frontend Dashboard',
            'description' => 'User is Frontend designer and has his own dashboard',
            'allowed_route' => 'frontend_dashboard',
        ]);

        // 2- create frontend dashboard permissions
         //===== Dashboard =====
        $manageMain = Permission::create(['name' => 'frontend_dashboard_main', 'display_name' => ['ar' => 'الرئيسية', 'en'    => 'Main'], 'route' => 'index', 'module' => 'index', 'as' => 'index', 'icon' => 'fa fa-home', 'parent' => '0', 'parent_original' => '0', 'sidebar_link' => '1', 'appear' => '1', 'ordering' => '1']);
        $manageMain->parent_show = $manageMain->id;
        $manageMain->save();

        // Main Menus
        $manageMainMenus = Permission::create(['name' => 'frontend_dashboard_manage_main_menus', 'display_name' => ['ar' => 'إدارة القوائم', 'en' => 'Manage Menus'], 'route' => 'main_menus', 'module' => 'main_menus', 'as' => 'main_menus.index', 'icon' => 'fa fa-list-ul', 'parent' => '0', 'parent_original' => '0', 'sidebar_link' => '1', 'appear' => '1', 'ordering' => '5',]);
        $manageMainMenus->parent_show = $manageMainMenus->id;
        $manageMainMenus->save();
        $showMainMenus    =  Permission::create(['name' => 'frontend_dashboard_show_main_menus',  'display_name' => ['ar'     => 'إدارة القائمة الرئيسية', 'en'  =>   'Main Menu'], 'route' => 'main_menus', 'module' => 'main_menus', 'as' => 'main_menus.index', 'icon' => 'fas fa-bars', 'parent' => $manageMainMenus->id, 'parent_original' => $manageMainMenus->id, 'parent_show' => $manageMainMenus->id, 'sidebar_link' => '1', 'appear' => '1']);
        $createMainMenus  =  Permission::create(['name' => 'frontend_dashboard_create_main_menus', 'display_name'  => ['ar'     => 'إضافة عنصر قائمة رئيسية', 'en'  =>  'Add Main Menu Item'], 'route' => 'main_menus', 'module' => 'main_menus', 'as' => 'main_menus.create', 'icon' => null, 'parent' => $manageMainMenus->id, 'parent_original' => $manageMainMenus->id, 'parent_show' => $manageMainMenus->id, 'sidebar_link' => '0', 'appear' => '0']);
        $displayMainMenus =  Permission::create(['name' => 'frontend_dashboard_display_main_menus', 'display_name'  => ['ar'     => 'عرض عنصر قائمة رئيسية', 'en'  =>  'Display Main Menu Item'], 'route' => 'main_menus', 'module' => 'main_menus', 'as' => 'main_menus.show', 'icon' => null, 'parent' => $manageMainMenus->id, 'parent_original' => $manageMainMenus->id, 'parent_show' => $manageMainMenus->id, 'sidebar_link' => '0', 'appear' => '0']);
        $updateMainMenus  =  Permission::create(['name' => 'frontend_dashboard_update_main_menus', 'display_name'  => ['ar'     => 'تعديل عنصر قائمة رئيسية', 'en'  =>  'Edit Main Menu Item'], 'route' => 'main_menus', 'module' => 'main_menus', 'as' => 'main_menus.edit', 'icon' => null, 'parent' => $manageMainMenus->id, 'parent_original' => $manageMainMenus->id, 'parent_show' => $manageMainMenus->id, 'sidebar_link' => '0', 'appear' => '0']);
        $deleteMainMenus  =  Permission::create(['name' => 'frontend_dashboard_delete_main_menus', 'display_name'  => ['ar'     => 'حذف عنصر قائمة رئيسية', 'en'  =>  'Delete Main Menu Item'], 'route' => 'main_menus', 'module' => 'main_menus', 'as' => 'main_menus.destroy', 'icon' => null, 'parent' => $manageMainMenus->id, 'parent_original' => $manageMainMenus->id, 'parent_show' => $manageMainMenus->id, 'sidebar_link' => '0', 'appear' => '0']);

        //SystemFeaturesMenu system_features_menus
        $manageSystemFeaturesMenus = Permission::create(['name' => 'frontend_dashboard_manage_system_features_menus', 'display_name' => ['ar'    =>  'إدارة قائمة مميزات النظام', 'en'   =>  'System Features Menu'], 'route' => 'system_features_menus', 'module' => 'system_features_menus', 'as' => 'system_features_menus.index', 'icon' => 'fas fa-bars', 'parent' => $manageMainMenus->id, 'parent_original' => $manageMainMenus->id, 'sidebar_link' => '1', 'appear' => '1', 'ordering' => '10',]);
        $manageSystemFeaturesMenus->parent_show = $manageSystemFeaturesMenus->id;
        $manageSystemFeaturesMenus->save();
        $showImportantLinkMenus    =  Permission::create(['name' => 'frontend_dashboard_show_system_features_menus',  'display_name' => ['ar'  =>  'إدارة قائمة مميزات النظام',   'en'    =>  'System Features Menu'], 'route' => 'system_features_menus', 'module' => 'system_features_menus', 'as' => 'system_features_menus.index', 'icon' => 'fas fa-bars', 'parent' => $manageSystemFeaturesMenus->id, 'parent_original' => $manageSystemFeaturesMenus->id, 'parent_show' => $manageSystemFeaturesMenus->id, 'sidebar_link' => '1', 'appear' => '1']);
        $createImportantLinkMenus  =  Permission::create(['name' => 'frontend_dashboard_create_system_features_menus', 'display_name'  => ['ar'  =>  'إضافة عنصر قائمة مميزات النظام ',   'en'    =>  'Add System Features Menu Item'], 'route' => 'system_features_menus', 'module' => 'system_features_menus', 'as' => 'system_features_menus.create', 'icon' => null, 'parent' => $manageSystemFeaturesMenus->id, 'parent_original' => $manageSystemFeaturesMenus->id, 'parent_show' => $manageSystemFeaturesMenus->id, 'sidebar_link' => '0', 'appear' => '0']);
        $displayImportantLinkMenus =  Permission::create(['name' => 'frontend_dashboard_display_system_features_menus', 'display_name'  => ['ar'  =>  'عرض عنصر قائمة مميزات النظام ',   'en'    =>  'Display System Features Menu Item'], 'route' => 'system_features_menus', 'module' => 'system_features_menus', 'as' => 'system_features_menus.show', 'icon' => null, 'parent' => $manageSystemFeaturesMenus->id, 'parent_original' => $manageSystemFeaturesMenus->id, 'parent_show' => $manageSystemFeaturesMenus->id, 'sidebar_link' => '0', 'appear' => '0']);
        $updateImportantLinkMenus  =  Permission::create(['name' => 'frontend_dashboard_update_system_features_menus', 'display_name'  => ['ar'  =>  'تعديل عنصر قائمة مميزات النظام ',   'en'    =>  'Edit System Features Menu Item'], 'route' => 'system_features_menus', 'module' => 'system_features_menus', 'as' => 'system_features_menus.edit', 'icon' => null, 'parent' => $manageSystemFeaturesMenus->id, 'parent_original' => $manageSystemFeaturesMenus->id, 'parent_show' => $manageSystemFeaturesMenus->id, 'sidebar_link' => '0', 'appear' => '0']);
        $deleteImportantLinkMenus  =  Permission::create(['name' => 'frontend_dashboard_delete_system_features_menus', 'display_name'  => ['ar'  =>  'حذف عنصر قائمة مميزات النظام ',   'en'    =>  'Delete System Features Menu Item'], 'route' => 'system_features_menus', 'module' => 'system_features_menus', 'as' => 'system_features_menus.destroy', 'icon' => null, 'parent' => $manageSystemFeaturesMenus->id, 'parent_original' => $manageSystemFeaturesMenus->id, 'parent_show' => $manageSystemFeaturesMenus->id, 'sidebar_link' => '0', 'appear' => '0']);

        //SystemModulesMenus system_modules_menus
        $SystemModulesMenus = Permission::create(['name' => 'frontend_dashboard_manage_system_modules_menus', 'display_name' => ['ar'    =>  'إدارة قائمة وحدات النظام', 'en'   =>  'System Modules Menu'], 'route' => 'system_modules_menus', 'module' => 'system_modules_menus', 'as' => 'system_modules_menus.index', 'icon' => 'fas fa-bars', 'parent' => $manageMainMenus->id, 'parent_original' => $manageMainMenus->id, 'sidebar_link' => '1', 'appear' => '1', 'ordering' => '10',]);
        $SystemModulesMenus->parent_show = $SystemModulesMenus->id;
        $SystemModulesMenus->save();
        $showImportantLinkMenus    =  Permission::create(['name' => 'frontend_dashboard_show_system_modules_menus',  'display_name' => ['ar'  =>  'إدارة قائمة وحدات النظام',   'en'    =>  'System Modules Menu'], 'route' => 'system_modules_menus', 'module' => 'system_modules_menus', 'as' => 'system_modules_menus.index', 'icon' => 'fas fa-bars', 'parent' => $SystemModulesMenus->id, 'parent_original' => $SystemModulesMenus->id, 'parent_show' => $SystemModulesMenus->id, 'sidebar_link' => '1', 'appear' => '1']);
        $createImportantLinkMenus  =  Permission::create(['name' => 'frontend_dashboard_create_system_modules_menus', 'display_name'  => ['ar'  =>  'إضافة عنصر قائمة وحدات النظام ',   'en'    =>  'Add System Modules Menu Item'], 'route' => 'system_modules_menus', 'module' => 'system_modules_menus', 'as' => 'system_modules_menus.create', 'icon' => null, 'parent' => $SystemModulesMenus->id, 'parent_original' => $SystemModulesMenus->id, 'parent_show' => $SystemModulesMenus->id, 'sidebar_link' => '0', 'appear' => '0']);
        $displayImportantLinkMenus =  Permission::create(['name' => 'frontend_dashboard_display_system_modules_menus', 'display_name'  => ['ar'  =>  'عرض عنصر قائمة وحدات النظام ',   'en'    =>  'Display System Modules Menu Item'], 'route' => 'system_modules_menus', 'module' => 'system_modules_menus', 'as' => 'system_modules_menus.show', 'icon' => null, 'parent' => $SystemModulesMenus->id, 'parent_original' => $SystemModulesMenus->id, 'parent_show' => $SystemModulesMenus->id, 'sidebar_link' => '0', 'appear' => '0']);
        $updateImportantLinkMenus  =  Permission::create(['name' => 'frontend_dashboard_update_system_modules_menus', 'display_name'  => ['ar'  =>  'تعديل عنصر قائمة وحدات النظام ',   'en'    =>  'Edit System Modules Menu Item'], 'route' => 'system_modules_menus', 'module' => 'system_modules_menus', 'as' => 'system_modules_menus.edit', 'icon' => null, 'parent' => $SystemModulesMenus->id, 'parent_original' => $SystemModulesMenus->id, 'parent_show' => $SystemModulesMenus->id, 'sidebar_link' => '0', 'appear' => '0']);
        $deleteImportantLinkMenus  =  Permission::create(['name' => 'frontend_dashboard_delete_system_modules_menus', 'display_name'  => ['ar'  =>  'حذف عنصر قائمة وحدات النظام ',   'en'    =>  'Delete System Modules Menu Item'], 'route' => 'system_modules_menus', 'module' => 'system_modules_menus', 'as' => 'system_modules_menus.destroy', 'icon' => null, 'parent' => $SystemModulesMenus->id, 'parent_original' => $SystemModulesMenus->id, 'parent_show' => $SystemModulesMenus->id, 'sidebar_link' => '0', 'appear' => '0']);


        //importantlink menu
        $manageImportantLinkMenus = Permission::create(['name' => 'frontend_dashboard_manage_important_link_menus', 'display_name' => ['ar'    =>  'إدارة قائمة روابط مهمة', 'en'   =>  'Important Link Menu'], 'route' => 'important_link_menus', 'module' => 'important_link_menus', 'as' => 'important_link_menus.index', 'icon' => 'fas fa-bars', 'parent' => $manageMainMenus->id, 'parent_original' => $manageMainMenus->id, 'sidebar_link' => '1', 'appear' => '1', 'ordering' => '10',]);
        $manageImportantLinkMenus->parent_show = $manageImportantLinkMenus->id;
        $manageImportantLinkMenus->save();
        $showImportantLinkMenus    =  Permission::create(['name' => 'frontend_dashboard_show_important_link_menus',  'display_name' => ['ar'  =>  'إدارة قائمة روابط مهمة',   'en'    =>  'Important Link Menu'], 'route' => 'important_link_menus', 'module' => 'important_link_menus', 'as' => 'important_link_menus.index', 'icon' => 'fas fa-bars', 'parent' => $manageImportantLinkMenus->id, 'parent_original' => $manageImportantLinkMenus->id, 'parent_show' => $manageImportantLinkMenus->id, 'sidebar_link' => '1', 'appear' => '1']);
        $createImportantLinkMenus  =  Permission::create(['name' => 'frontend_dashboard_create_important_link_menus', 'display_name'  => ['ar'  =>  'إضافة عنصر قائمة روابط مهمة ',   'en'    =>  'Add Important Link Menu Item'], 'route' => 'important_link_menus', 'module' => 'important_link_menus', 'as' => 'important_link_menus.create', 'icon' => null, 'parent' => $manageImportantLinkMenus->id, 'parent_original' => $manageImportantLinkMenus->id, 'parent_show' => $manageImportantLinkMenus->id, 'sidebar_link' => '0', 'appear' => '0']);
        $displayImportantLinkMenus =  Permission::create(['name' => 'frontend_dashboard_display_important_link_menus', 'display_name'  => ['ar'  =>  'عرض عنصر قائمة روابط مهمة ',   'en'    =>  'Display Important Link Menu Item'], 'route' => 'important_link_menus', 'module' => 'important_link_menus', 'as' => 'important_link_menus.show', 'icon' => null, 'parent' => $manageImportantLinkMenus->id, 'parent_original' => $manageImportantLinkMenus->id, 'parent_show' => $manageImportantLinkMenus->id, 'sidebar_link' => '0', 'appear' => '0']);
        $updateImportantLinkMenus  =  Permission::create(['name' => 'frontend_dashboard_update_important_link_menus', 'display_name'  => ['ar'  =>  'تعديل عنصر قائمة روابط مهمة ',   'en'    =>  'Edit Important Link Menu Item'], 'route' => 'important_link_menus', 'module' => 'important_link_menus', 'as' => 'important_link_menus.edit', 'icon' => null, 'parent' => $manageImportantLinkMenus->id, 'parent_original' => $manageImportantLinkMenus->id, 'parent_show' => $manageImportantLinkMenus->id, 'sidebar_link' => '0', 'appear' => '0']);
        $deleteImportantLinkMenus  =  Permission::create(['name' => 'frontend_dashboard_delete_important_link_menus', 'display_name'  => ['ar'  =>  'حذف عنصر قائمة روابط مهمة ',   'en'    =>  'Delete Important Link Menu Item'], 'route' => 'important_link_menus', 'module' => 'important_link_menus', 'as' => 'important_link_menus.destroy', 'icon' => null, 'parent' => $manageImportantLinkMenus->id, 'parent_original' => $manageImportantLinkMenus->id, 'parent_show' => $manageImportantLinkMenus->id, 'sidebar_link' => '0', 'appear' => '0']);


        //main sliders
        $manageMainSliders = Permission::create(['name' => 'frontend_dashboard_manage_main_sliders', 'display_name' => ['ar'    =>  'إدارة عارض الشرائح', 'en' =>  'Manage Slide Viewer'], 'route' => 'main_sliders', 'module' => 'main_sliders', 'as' => 'main_sliders.index', 'icon' => 'fas fa-sliders-h', 'parent' => '0', 'parent_original' => '0', 'sidebar_link' => '1', 'appear' => '1', 'ordering' => '15',]);
        $manageMainSliders->parent_show = $manageMainSliders->id;
        $manageMainSliders->save();
        $showMainSliders    =  Permission::create(['name' => 'frontend_dashboard_show_main_sliders', 'display_name'    =>  ['ar'    =>  ' عارض الشرائح الرئيسي',   'en'    =>  'Main Slide Viewer'], 'route' => 'main_sliders', 'module' => 'main_sliders', 'as' => 'main_sliders.index', 'icon' => 'fas  fa-sliders-h', 'parent' => $manageMainSliders->id, 'parent_original' => $manageMainSliders->id, 'parent_show' => $manageMainSliders->id, 'sidebar_link' => '1', 'appear' => '1']);
        $createMainSliders  =  Permission::create(['name' => 'frontend_dashboard_create_main_sliders', 'display_name'    =>  ['ar'    =>  'إضافة شريحة جديد',   'en'    =>  'Add Slide'], 'route' => 'main_sliders', 'module' => 'main_sliders', 'as' => 'main_sliders.create', 'icon' => null, 'parent' => $manageMainSliders->id, 'parent_original' => $manageMainSliders->id, 'parent_show' => $manageMainSliders->id, 'sidebar_link' => '0', 'appear' => '0']);
        $displayMainSliders =  Permission::create(['name' => 'frontend_dashboard_display_main_sliders', 'display_name'    =>  ['ar'    =>  'عرض الشريحة',   'en'    =>  'Display Main Slide'],  'route' => 'main_sliders', 'module' => 'main_sliders', 'as' => 'main_sliders.show', 'icon' => null, 'parent' => $manageMainSliders->id, 'parent_original' => $manageMainSliders->id, 'parent_show' => $manageMainSliders->id, 'sidebar_link' => '0', 'appear' => '0']);
        $updateMainSliders  =  Permission::create(['name' => 'frontend_dashboard_update_main_sliders', 'display_name'    =>  ['ar'    =>  'تعديل الشريحة',   'en'    =>  'Edit Main Slide'],  'route' => 'main_sliders', 'module' => 'main_sliders', 'as' => 'main_sliders.edit', 'icon' => null, 'parent' => $manageMainSliders->id, 'parent_original' => $manageMainSliders->id, 'parent_show' => $manageMainSliders->id, 'sidebar_link' => '0', 'appear' => '0']);
        $deleteMainSliders  =  Permission::create(['name' => 'frontend_dashboard_delete_main_sliders', 'display_name'    =>  ['ar'    =>  'حذف الشريحة',   'en'    =>  'Delete Main Slide'],  'route' => 'main_sliders', 'module' => 'main_sliders', 'as' => 'main_sliders.destroy', 'icon' => null, 'parent' => $manageMainSliders->id, 'parent_original' => $manageMainSliders->id, 'parent_show' => $manageMainSliders->id, 'sidebar_link' => '0', 'appear' => '0']);

        //Advertisor sliders
        $manageAdvertisorSliders = Permission::create(['name' => 'frontend_dashboard_manage_advertisor_sliders', 'display_name' => ['ar'    =>  'عارض شرائح الإعلانات', 'en'   =>  'Adv Slide Viewer'], 'route' => 'advertisor_sliders', 'module' => 'advertisor_sliders', 'as' => 'advertisor_sliders.index', 'icon' => 'fas fa-bullhorn', 'parent' => $manageMainSliders->id, 'parent_original' => '0', 'sidebar_link' => '1', 'appear' => '1', 'ordering' => '20',]);
        $manageAdvertisorSliders->parent_show = $manageAdvertisorSliders->id;
        $manageAdvertisorSliders->save();
        $showAdvertisorSliders    =  Permission::create(['name' => 'frontend_dashboard_show_advertisor_sliders', 'display_name'    =>  ['ar'   =>  'عارض شرائح الإعلانات',   'en'    =>  'Adv Slide Viewer'], 'route' => 'advertisor_sliders', 'module' => 'advertisor_sliders', 'as' => 'advertisor_sliders.index', 'icon' => 'fas fa-bullhorn', 'parent' => $manageAdvertisorSliders->id, 'parent_original' => $manageAdvertisorSliders->id, 'parent_show' => $manageAdvertisorSliders->id, 'sidebar_link' => '1', 'appear' => '1']);
        $createAdvertisorSliders  =  Permission::create(['name' => 'frontend_dashboard_create_advertisor_sliders', 'display_name'    =>  ['ar'   =>  'إضافة شريحة جديد',   'en'    =>  'Add Adv Slide'], 'route' => 'advertisor_sliders', 'module' => 'advertisor_sliders', 'as' => 'advertisor_sliders.create', 'icon' => null, 'parent' => $manageAdvertisorSliders->id, 'parent_original' => $manageAdvertisorSliders->id, 'parent_show' => $manageAdvertisorSliders->id, 'sidebar_link' => '0', 'appear' => '0']);
        $displayAdvertisorSliders =  Permission::create(['name' => 'frontend_dashboard_display_advertisor_sliders', 'display_name'    =>  ['ar'   =>  'عرض الشريحة',   'en'    =>  'Display Adv Slide'],  'route' => 'advertisor_sliders', 'module' => 'advertisor_sliders', 'as' => 'advertisor_sliders.show', 'icon' => null, 'parent' => $manageAdvertisorSliders->id, 'parent_original' => $manageAdvertisorSliders->id, 'parent_show' => $manageAdvertisorSliders->id, 'sidebar_link' => '0', 'appear' => '0']);
        $updateAdvertisorSliders  =  Permission::create(['name' => 'frontend_dashboard_update_advertisor_sliders', 'display_name'    =>  ['ar'   =>  'تعديل الشريحة',   'en'    =>  'Edit Adv Slide'],  'route' => 'advertisor_sliders', 'module' => 'advertisor_sliders', 'as' => 'advertisor_sliders.edit', 'icon' => null, 'parent' => $manageAdvertisorSliders->id, 'parent_original' => $manageAdvertisorSliders->id, 'parent_show' => $manageAdvertisorSliders->id, 'sidebar_link' => '0', 'appear' => '0']);
        $deleteAdvertisorSliders  =  Permission::create(['name' => 'frontend_dashboard_delete_advertisor_sliders', 'display_name'    =>  ['ar'   =>  'حذف الشريحة',   'en'    =>  'Delete Adv Slide'],  'route' => 'advertisor_sliders', 'module' => 'advertisor_sliders', 'as' => 'advertisor_sliders.destroy', 'icon' => null, 'parent' => $manageAdvertisorSliders->id, 'parent_original' => $manageAdvertisorSliders->id, 'parent_show' => $manageAdvertisorSliders->id, 'sidebar_link' => '0', 'appear' => '0']);


        // Partners
        $managePartners = Permission::create(['name' => 'frontend_dashboard_manage_partners', 'display_name' => ['ar'  =>  'شركاؤنا',    'en'    =>  'Our Partners'], 'route' => 'partners', 'module' => 'partners', 'as' => 'partners.index', 'icon' => 'far fa-handshake', 'parent' => '0', 'parent_original' => '0', 'sidebar_link' => '1', 'appear' => '1', 'ordering' => '25',]);
        $managePartners->parent_show = $managePartners->id;
        $managePartners->save();
        $showPartners   =  Permission::create(['name'  => 'frontend_dashboard_show_partners', 'display_name'       =>  ['ar'   =>  'شركاؤنا',   'en'    =>  'Our Partners'], 'route' => 'partners', 'module' => 'partners', 'as' => 'partners.index', 'icon' => 'far fa-handshake', 'parent' => $managePartners->id, 'parent_original' => $managePartners->id, 'parent_show' => $managePartners->id, 'sidebar_link' => '0', 'appear' => '0']);
        $createPartners =  Permission::create(['name'  => 'frontend_dashboard_create_partners', 'display_name'     =>  ['ar'   =>  'إنشاء شريك',   'en'    =>  'Create Our Partner'], 'route' => 'partners', 'module' => 'partners', 'as' => 'partners.create', 'icon' => null, 'parent' => $managePartners->id, 'parent_original' => $managePartners->id, 'parent_show' => $managePartners->id, 'sidebar_link' => '0', 'appear' => '0']);
        $displayPartners =  Permission::create(['name' => 'frontend_dashboard_display_partners', 'display_name'    =>  ['ar'   =>  'عرض شريك',   'en'    =>  'Display Our Partner'], 'route' => 'partners', 'module' => 'partners', 'as' => 'partners.show', 'icon' => null, 'parent' => $managePartners->id, 'parent_original' => $managePartners->id, 'parent_show' => $managePartners->id, 'sidebar_link' => '0', 'appear' => '0']);
        $updatePartners  =  Permission::create(['name' => 'frontend_dashboard_update_partners', 'display_name'     =>  ['ar'   =>  'تعديل شريك',   'en'    =>  'Edit Our Partner'], 'route' => 'partners', 'module' => 'partners', 'as' => 'partners.edit', 'icon' => null, 'parent' => $managePartners->id, 'parent_original' => $managePartners->id, 'parent_show' => $managePartners->id, 'sidebar_link' => '0', 'appear' => '0']);
        $deletePartners =  Permission::create(['name'  => 'frontend_dashboard_delete_partners', 'display_name'     =>  ['ar'   =>  'حذف شريك',   'en'    =>  'Delete Our Partner'], 'route' => 'partners', 'module' => 'partners', 'as' => 'partners.destroy', 'icon' => null, 'parent' => $managePartners->id, 'parent_original' => $managePartners->id, 'parent_show' => $managePartners->id, 'sidebar_link' => '0', 'appear' => '0']);


         //page Categories
        $managePageCategories = Permission::create(['name' => 'frontend_dashboard_manage_page_categories', 'display_name' => ['ar' => 'إدارة الصفحات', 'en' => 'Manage Pages'], 'route' => 'page_categories', 'module' => 'page_categories', 'as' => 'page_categories.index', 'icon' => 'far fa-file-alt', 'parent' => '0', 'parent_original' => '0', 'sidebar_link' => '1', 'appear' => '1', 'ordering' => '30',]);
        $managePageCategories->parent_show = $managePageCategories->id;
        $managePageCategories->save();
        $showPages    =  Permission::create(['name' => 'frontend_dashboard_show_page_categories',  'display_name' => ['ar'     => 'إدارة تصنيف الصفحات ', 'en'  =>   'manage Page Categories'], 'route' => 'page_categories', 'module' => 'page_categories', 'as' => 'page_categories.index', 'icon' => 'far fa-file-alt', 'parent' => $managePageCategories->id, 'parent_original' => $managePageCategories->id, 'parent_show' => $managePageCategories->id, 'sidebar_link' => '1', 'appear' => '1']);
        $createPages  =  Permission::create(['name' => 'frontend_dashboard_create_page_categories', 'display_name'  => ['ar'     => 'إضافة تصنيف صفحة', 'en'  =>  'Add Page Category'], 'route' => 'page_categories', 'module' => 'page_categories', 'as' => 'page_categories.create', 'icon' => null, 'parent' => $managePageCategories->id, 'parent_original' => $managePageCategories->id, 'parent_show' => $managePageCategories->id, 'sidebar_link' => '0', 'appear' => '0']);
        $displayPages =  Permission::create(['name' => 'frontend_dashboard_display_page_categories', 'display_name'  => ['ar'     => 'عرض تصنيف صفحة', 'en'  =>  'Display Page Category'], 'route' => 'page_categories', 'module' => 'page_categories', 'as' => 'page_categories.show', 'icon' => null, 'parent' => $managePageCategories->id, 'parent_original' => $managePageCategories->id, 'parent_show' => $managePageCategories->id, 'sidebar_link' => '0', 'appear' => '0']);
        $updatePages  =  Permission::create(['name' => 'frontend_dashboard_update_page_categories', 'display_name'  => ['ar'     => 'تعديل تصنيف صفحة', 'en'  =>  'Edit Page Category'], 'route' => 'page_categories', 'module' => 'page_categories', 'as' => 'page_categories.edit', 'icon' => null, 'parent' => $managePageCategories->id, 'parent_original' => $managePageCategories->id, 'parent_show' => $managePageCategories->id, 'sidebar_link' => '0', 'appear' => '0']);
        $deletePages  =  Permission::create(['name' => 'frontend_dashboard_delete_page_categories', 'display_name'  => ['ar'     => 'حذف تصنيف صفحة', 'en'  =>  'Delete Page Category'], 'route' => 'page_categories', 'module' => 'page_categories', 'as' => 'page_categories.destroy', 'icon' => null, 'parent' => $managePageCategories->id, 'parent_original' => $managePageCategories->id, 'parent_show' => $managePageCategories->id, 'sidebar_link' => '0', 'appear' => '0']);

        //pages
        $managePages = Permission::create(['name' => 'frontend_dashboard_manage_pages', 'display_name' => ['ar' => 'إدارة الصفحات', 'en' => 'Manage Pages'], 'route' => 'pages', 'module' => 'pages', 'as' => 'pages.index', 'icon' => 'far fa-file-alt', 'parent' => $managePageCategories->id, 'parent_original' => '0', 'sidebar_link' => '1', 'appear' => '1', 'ordering' => '35',]);
        $managePages->parent_show = $managePages->id;
        $managePages->save();
        $showPages    =  Permission::create(['name' => 'frontend_dashboard_show_pages',  'display_name' => ['ar'     => 'إدارة الصفحة ', 'en'  =>   'Main Page'], 'route' => 'pages', 'module' => 'pages', 'as' => 'pages.index', 'icon' => 'far fa-file-alt', 'parent' => $managePages->id, 'parent_original' => $managePages->id, 'parent_show' => $managePages->id, 'sidebar_link' => '0', 'appear' => '0']);
        $createPages  =  Permission::create(['name' => 'frontend_dashboard_create_pages', 'display_name'  => ['ar'     => 'إضافة صفحة', 'en'  =>  'Add Page'], 'route' => 'pages', 'module' => 'pages', 'as' => 'pages.create', 'icon' => null, 'parent' => $managePages->id, 'parent_original' => $managePages->id, 'parent_show' => $managePages->id, 'sidebar_link' => '0', 'appear' => '0']);
        $displayPages =  Permission::create(['name' => 'frontend_dashboard_display_pages', 'display_name'  => ['ar'     => 'عرض صفحة', 'en'  =>  'Display Page'], 'route' => 'pages', 'module' => 'pages', 'as' => 'pages.show', 'icon' => null, 'parent' => $managePages->id, 'parent_original' => $managePages->id, 'parent_show' => $managePages->id, 'sidebar_link' => '0', 'appear' => '0']);
        $updatePages  =  Permission::create(['name' => 'frontend_dashboard_update_pages', 'display_name'  => ['ar'     => 'تعديل صفحة', 'en'  =>  'Edit Page'], 'route' => 'pages', 'module' => 'pages', 'as' => 'pages.edit', 'icon' => null, 'parent' => $managePages->id, 'parent_original' => $managePages->id, 'parent_show' => $managePages->id, 'sidebar_link' => '0', 'appear' => '0']);
        $deletePages  =  Permission::create(['name' => 'frontend_dashboard_delete_pages', 'display_name'  => ['ar'     => 'حذف صفحة', 'en'  =>  'Delete Page'], 'route' => 'pages', 'module' => 'pages', 'as' => 'pages.destroy', 'icon' => null, 'parent' => $managePages->id, 'parent_original' => $managePages->id, 'parent_show' => $managePages->id, 'sidebar_link' => '0', 'appear' => '0']);

        //Testimonials
        $manageTestimonials = Permission::create(['name' => 'frontend_dashboard_manage_testimonials', 'display_name' => ['ar'   =>  'إدارة ماذا يقولوا عنا',   'en'    =>  'Manage Testimonials'], 'route' => 'testimonials', 'module' => 'testimonials', 'as' => 'testimonials.index', 'icon' => 'fas fa-certificate', 'parent' => '0', 'parent_original' => '0', 'sidebar_link' => '1', 'appear' => '1', 'ordering' => '40',]);
        $manageTestimonials->parent_show = $manageTestimonials->id;
        $manageTestimonials->save();
        $showTestimonials   =  Permission::create(['name'  => 'frontend_dashboard_show_testimonials', 'display_name'        =>  ['ar'   =>  'ماذا يقولوا عنا',   'en'    =>  'Testimonials'], 'route' => 'testimonials', 'module' => 'testimonials', 'as' => 'testimonials.index', 'icon' => 'fas fa-certificate', 'parent' => $manageTestimonials->id, 'parent_original' => $manageTestimonials->id, 'parent_show' => $manageTestimonials->id, 'sidebar_link' => '0', 'appear' => '0']);
        $createTestimonials =  Permission::create(['name'  => 'frontend_dashboard_create_testimonials', 'display_name'      =>  ['ar'   =>  'إضافة ماذا يقولوا عنا جديدة',   'en'    =>  'Create New Testimonial'], 'route' => 'testimonials/create', 'module' => 'testimonials', 'as' => 'testimonials.create', 'icon' => null, 'parent' => $manageTestimonials->id, 'parent_original' => $manageTestimonials->id, 'parent_show' => $manageTestimonials->id, 'sidebar_link' => '0', 'appear' => '0']);
        $displayTestimonials =  Permission::create(['name' => 'frontend_dashboard_display_testimonials', 'display_name'     =>  ['ar'   =>  'عرض ماذا يقولوا عنا',   'en'    =>  'Dispay Testimonial'], 'route' => 'testimonials/{testimonials}', 'module' => 'testimonials', 'as' => 'testimonials.show', 'icon' => null, 'parent' => $manageTestimonials->id, 'parent_original' => $manageTestimonials->id, 'parent_show' => $manageTestimonials->id, 'sidebar_link' => '0', 'appear' => '0']);
        $updateTestimonials  =  Permission::create(['name' => 'frontend_dashboard_update_testimonials', 'display_name'      =>  ['ar'   =>  'تعديل ماذا يقولوا عنا',   'en'    =>  'Edit Testimonial'], 'route' => 'testimonials/{testimonials}/edit', 'module' => 'testimonials', 'as' => 'testimonials.edit', 'icon' => null, 'parent' => $manageTestimonials->id, 'parent_original' => $manageTestimonials->id, 'parent_show' => $manageTestimonials->id, 'sidebar_link' => '0', 'appear' => '0']);
        $deleteTestimonials =  Permission::create(['name'  => 'frontend_dashboard_delete_testimonials', 'display_name'      =>  ['ar'   =>  'حذف ماذا يقولوا عنا',   'en'    =>  'Delete Testimonial'], 'route' => 'testimonials/{testimonials}', 'module' => 'testimonials', 'as' => 'testimonials.destroy', 'icon' => null, 'parent' => $manageTestimonials->id, 'parent_original' => $manageTestimonials->id, 'parent_show' => $manageTestimonials->id, 'sidebar_link' => '0', 'appear' => '0']);


         //Common Questions
        $manageCommonQuestions = Permission::create(['name' => 'frontend_dashboard_manage_common_questions', 'display_name' => ['ar'   =>  'إدارة الاسئلة الشائعة',   'en'    =>  'Asked Questions'], 'route' => 'common_questions', 'module' => 'common_questions', 'as' => 'common_questions.index', 'icon' => 'fas fa-question', 'parent' => '0', 'parent_original' => '0', 'sidebar_link' => '1', 'appear' => '1', 'ordering' => '45',]);
        $manageCommonQuestions->parent_show = $manageCommonQuestions->id;
        $manageCommonQuestions->save();
        $showCommonQuestions   =  Permission::create(['name'  => 'frontend_dashboard_show_common_questions', 'display_name'        =>  ['ar'   =>  'الاسئلة الشائعة',   'en'    =>  'Questions'], 'route' => 'common_questions', 'module' => 'common_questions', 'as' => 'common_questions.index', 'icon' => 'fas fa-question', 'parent' => $manageCommonQuestions->id, 'parent_original' => $manageCommonQuestions->id, 'parent_show' => $manageCommonQuestions->id, 'sidebar_link' => '1', 'appear' => '1']);
        $createCommonQuestions =  Permission::create(['name'  => 'frontend_dashboard_create_common_questions', 'display_name'      =>  ['ar'   =>  'إنشاء سؤال',   'en'    =>  'Create Question'], 'route' => 'common_questions/create', 'module' => 'common_questions', 'as' => 'common_questions.create', 'icon' => null, 'parent' => $manageCommonQuestions->id, 'parent_original' => $manageCommonQuestions->id, 'parent_show' => $manageCommonQuestions->id, 'sidebar_link' => '1', 'appear' => '0']);
        $displayCommonQuestions =  Permission::create(['name' => 'frontend_dashboard_display_common_questions', 'display_name'     =>  ['ar'   =>  'عرض سؤال',   'en'    =>  'Dispay Question'], 'route' => 'common_questions/{common_questions}', 'module' => 'common_questions', 'as' => 'common_questions.show', 'icon' => null, 'parent' => $manageCommonQuestions->id, 'parent_original' => $manageCommonQuestions->id, 'parent_show' => $manageCommonQuestions->id, 'sidebar_link' => '0', 'appear' => '0']);
        $updateCommonQuestions  =  Permission::create(['name' => 'frontend_dashboard_update_common_questions', 'display_name'      =>  ['ar'   =>  'تعديل سؤال',   'en'    =>  'Edit Question'], 'route' => 'common_questions/{common_questions}/edit', 'module' => 'common_questions', 'as' => 'common_questions.edit', 'icon' => null, 'parent' => $manageCommonQuestions->id, 'parent_original' => $manageCommonQuestions->id, 'parent_show' => $manageCommonQuestions->id, 'sidebar_link' => '0', 'appear' => '0']);
        $deleteCommonQuestions =  Permission::create(['name'  => 'frontend_dashboard_delete_common_questions', 'display_name'      =>  ['ar'   =>  'حذف سؤال',   'en'    =>  'Delete Question'], 'route' => 'common_questions/{common_questions}', 'module' => 'common_questions', 'as' => 'common_questions.destroy', 'icon' => null, 'parent' => $manageCommonQuestions->id, 'parent_original' => $manageCommonQuestions->id, 'parent_show' => $manageCommonQuestions->id, 'sidebar_link' => '0', 'appear' => '0']);

        // Statistics
        $manageStatistics = Permission::create(['name' => 'frontend_dashboard_manage_Statistics', 'display_name' => ['ar'  =>  'إدارة الإحصائيات',    'en'    =>  'Manage Statistics'], 'route' => 'statistics', 'module' => 'statistics', 'as' => 'statistics.index', 'icon' => 'far fa-calendar-alt', 'parent' => '0', 'parent_original' => '0', 'sidebar_link' => '1', 'appear' => '1', 'ordering' => '140',]);
        $manageStatistics->parent_show = $manageStatistics->id;
        $manageStatistics->save();
        $showStatistics   =  Permission::create(['name'  => 'frontend_dashboard_show_Statistics', 'display_name'       =>  ['ar'   =>  'الإحصائيات',   'en'    =>  'Statistics'], 'route' => 'statistics', 'module' => 'statistics', 'as' => 'statistics.index', 'icon' => 'far fa-calendar-alt', 'parent' => '0', 'parent_original' => '0', 'parent_show' => '0', 'sidebar_link' => '0', 'appear' => '0']);
        $createStatistics =  Permission::create(['name'  => 'frontend_dashboard_create_Statistics', 'display_name'     =>  ['ar'   =>  'إنشاء إحصاء جديد',   'en'    =>  'Create Statistic'], 'route' => 'statistics', 'module' => 'statistics', 'as' => 'statistics.create', 'icon' => null, 'parent' => '0', 'parent_original' => '0', 'parent_show' => '0', 'sidebar_link' => '0', 'appear' => '0']);
        $displayStatistics =  Permission::create(['name' => 'frontend_dashboard_display_Statistics', 'display_name'    =>  ['ar'   =>  'عرض إحصاء',   'en'    =>  'Display Statistic'], 'route' => 'statistics', 'module' => 'statistics', 'as' => 'statistics.show', 'icon' => null, 'parent' => '0', 'parent_original' => '0', 'parent_show' => '0', 'sidebar_link' => '0', 'appear' => '0']);
        $updateStatistics  =  Permission::create(['name' => 'frontend_dashboard_update_Statistics', 'display_name'     =>  ['ar'   =>  'تعديل إحصاء',   'en'    =>  'Edit Statistic'], 'route' => 'statistics', 'module' => 'statistics', 'as' => 'statistics.edit', 'icon' => null, 'parent' => '0', 'parent_original' => '0', 'parent_show' => '0', 'sidebar_link' => '0', 'appear' => '0']);
        $deleteStatistics =  Permission::create(['name'  => 'frontend_dashboard_delete_Statistics', 'display_name'     =>  ['ar'   =>  'حذف إحصاء',   'en'    =>  'Delete Statistic'], 'route' => 'statistics', 'module' => 'statistics', 'as' => 'statistics.destroy', 'icon' => null, 'parent' => '0', 'parent_original' => '0', 'parent_show' => '0', 'sidebar_link' => '0', 'appear' => '0']);


        //Site Settings Holder
        $manageSiteSettings = Permission::create(['name' => 'frontend_dashboard_manage_site_settings', 'display_name' => ['ar' =>  'الاعدادات العامة', 'en'    =>  'General Settings'], 'route' => 'settings', 'module' => 'settings', 'as' => 'settings.index', 'icon' => 'fa fa-cog', 'parent' => '0', 'parent_original' => '0', 'sidebar_link' => '1', 'appear' => '1', 'ordering' => '180',]);
        $manageSiteSettings->parent_show = $manageSiteSettings->id;
        $manageSiteSettings->save();

        // Site Infos
        $displaySiteInfos =  Permission::create(['name' => 'frontend_dashboard_display_site_infos', 'display_name'     => ['ar'   =>  'إدارة  بيانات الموقع', 'en'  =>  'Manage Site Infos'], 'route' => 'settings.site_main_infos', 'module' => 'settings.site_main_infos', 'as' => 'settings.site_main_infos.show', 'icon' => 'fa fa-info-circle', 'parent' => $manageSiteSettings->id, 'parent_original' => $manageSiteSettings->id, 'parent_show' => $manageSiteSettings->id, 'sidebar_link' => '1', 'appear' => '1']);
        $updateSiteInfos  =  Permission::create(['name' => 'frontend_dashboard_update_site_infos', 'display_name'      => ['ar'    =>  'تعديل بيانات الموقع', 'en'    =>  'Edit Site Infos'], 'route' => 'settings.site_main_infos', 'module' => 'settings.site_main_infos', 'as' => 'settings.site_main_infos.edit', 'icon' => null, 'parent' => $manageSiteSettings->id, 'parent_original' => $manageSiteSettings->id, 'parent_show' => $manageSiteSettings->id, 'sidebar_link' => '0', 'appear' => '0']);

        // Site Contacts
        $displaySiteContacts =  Permission::create(['name' => 'frontend_dashboard_display_site_contacts', 'display_name'   => ['ar'    =>  'إدارة  بيانات الإتصال ', 'en' =>  'Manage Site Contact '], 'route' => 'settings.site_contacts', 'module' => 'settings.site_contacts', 'as' => 'settings.site_contacts.show', 'icon' => 'fa fa-address-book', 'parent' => $manageSiteSettings->id, 'parent_original' => $manageSiteSettings->id, 'parent_show' => $manageSiteSettings->id, 'sidebar_link' => '1', 'appear' => '1']);
        $updateSiteContacts  =  Permission::create(['name' => 'frontend_dashboard_update_site_contacts', 'display_name'    => ['ar'    =>  'تعديل بيانات الإتصال ', 'en'   =>  'Edit Site Contact '], 'route' => 'settings.site_contacts', 'module' => 'settings.site_contacts', 'as' => 'settings.site_contacts.edit', 'icon' => null, 'parent' => $manageSiteSettings->id, 'parent_original' => $manageSiteSettings->id, 'parent_show' => $manageSiteSettings->id, 'sidebar_link' => '0', 'appear' => '0']);

        // Site Socials
        $displaySiteSocails =  Permission::create(['name' => 'frontend_dashboard_display_site_socials', 'display_name'     =>  ['ar'   =>  ' إدارة  حسابات التواصل  ',   'en'    =>  'Manage Site Socials'], 'route' => 'settings.site_socials', 'module' => 'settings.site_socials', 'as' => 'settings.site_socials.show', 'icon' => 'fas fa-rss', 'parent' => $manageSiteSettings->id, 'parent_original' => $manageSiteSettings->id, 'parent_show' => $manageSiteSettings->id, 'sidebar_link' => '1', 'appear' => '1']);
        $updateSiteSocails  =  Permission::create(['name' => 'frontend_dashboard_update_site_socials', 'display_name'      =>  ['ar'   =>  'تعديل حسابات التواصل ',   'en'    =>  'Edit Site Contact Infos'], 'route' => 'settings.site_socials', 'module' => 'settings.site_socials', 'as' => 'settings.site_socials.edit', 'icon' => null, 'parent' => $manageSiteSettings->id, 'parent_original' => $manageSiteSettings->id, 'parent_show' => $manageSiteSettings->id, 'sidebar_link' => '0', 'appear' => '0']);

        // Site SEO
        $displaySiteMetas =  Permission::create(['name' => 'frontend_dashboard_display_site_meta', 'display_name'     =>  ['ar'   =>  'إدارة  SEO',   'en'    =>  'Manage Site SEO'], 'route' => 'settings.site_meta', 'module' => 'settings.site_meta', 'as' => 'settings.site_meta.show', 'icon' => 'fa fa-tag', 'parent' => $manageSiteSettings->id, 'parent_original' => $manageSiteSettings->id, 'parent_show' => $manageSiteSettings->id, 'sidebar_link' => '1', 'appear' => '1']);
        $updateSiteMetas  =  Permission::create(['name' => 'frontend_dashboard_update_site_meta', 'display_name'      =>  ['ar'   =>  'تعديل SEO',   'en'    =>  'Edit Site SEO'], 'route' => 'settings.site_meta', 'module' => 'settings.site_meta', 'as' => 'settings.site_meta.edit', 'icon' => null, 'parent' => $manageSiteSettings->id, 'parent_original' => $manageSiteSettings->id, 'parent_show' => $manageSiteSettings->id, 'sidebar_link' => '0', 'appear' => '0']);

        // 3- attatch role to permssions
        $permissions = [
            // Dashboard
            $manageMain,
            // Main Menus
            $manageMainMenus,$showMainMenus,$createMainMenus,$displayMainMenus,$updateMainMenus,$deleteMainMenus,
            // Important Link Menus
            $manageImportantLinkMenus,$showImportantLinkMenus,$createImportantLinkMenus,$displayImportantLinkMenus,$updateImportantLinkMenus,$deleteImportantLinkMenus,
            // Main Sliders
            $manageMainSliders,$showMainSliders,$createMainSliders,$displayMainSliders,$updateMainSliders,$deleteMainSliders,
            // Advertisor Sliders
            $manageAdvertisorSliders,$showAdvertisorSliders,$createAdvertisorSliders,$displayAdvertisorSliders,$updateAdvertisorSliders,$deleteAdvertisorSliders,
            // Partners
            $managePartners,$showPartners,$createPartners,$displayPartners,$updatePartners,$deletePartners,
            //

        ];

        foreach ($permissions as $permission) {
            if (!$frontendRole->hasPermission($permission->name)) {
                $frontendRole->attachPermission($permission);
            }
        }

        $this->command->info('تم إنشاء صلاحيات واجهة التحكم frontend  وربطها بالدور بنجاح!');
    }
}
